version: '3'
services:
  app:
    container_name: album-app-backend
    image: album-app-backend
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=albums
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres